maneu/urls.py
from django.urls import include
from django.urls import path

from maneu.views import *

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('sendsms/', sendsms, name='sendsms'),
    path('login_api/', login_api, name='login_api'),
    path('maneu_admin/', include('maneu_admin.urls')),
    path('maneu_guest/', include('maneu_guest.urls')),
    path('maneu_index/', include('maneu_index.urls')),
    path('maneu_order/', include('maneu_order.urls')),
    path('maneu_report/', include('maneu_report.urls')),
]

maneu_guest/urls.py
from django.urls import path

from maneu_guest import views, api

app_name = 'maneu_guest'

urlpatterns = [
    path('', views.index, name='index'),
    path('insert/', views.insert, name='insert'),
    path('detail/', views.detail, name='detail'),
    path('api_search/', api.search, name='api_search'),
    path('api_insert/', api.insert, name='api_insert'),
    path('api_delete/', api.delete, name='api_delete'),
    path('api_detail/', api.detail, name='api_detail'),
    path('api_update/', api.update, name='api_update'),
]

maneu_order_v2/urls.py
from django.urls import path

from maneu_order_v2 import views

app_name = 'maneu_order_v2'
urlpatterns = [
    # views
    path('index/', views.index, name='index'),
    path('delete/', views.delete, name='delete'),
    path('detail/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
    path('insert/', views.insert, name='insert'),
    path('update/', views.update, name='update'),
    path('test1/', views.test1, name='test'),
]

user/urls.py
from django.urls import path

from user import api
from user import views

app_name = 'user'
urlpatterns = [
    # view
    path('list/', views.user_list, name='user_list'),
    path('logout/', views.user_logout, name='user_logout'),
    path('insert/', views.user_insert, name='user_insert'),
    path('update/', views.user_update, name='user_update'),
    path('detail/', views.user_detail, name='user_detail'),

    # api
    path('api_list/', api.user_list, name='api_user_list'),
    path('api_insert/', api.user_insert, name='api_user_insert'),
]

common/forms/InsertForm.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets


class UserInsertForm(forms.Form):
    username = forms.CharField(label="账号",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'username', 'class': 'form-control', 'placeholder': '账号'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入账号'},
                               )

    password = forms.CharField(label="密码",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'password', 'class': 'form-control', 'placeholder': '密码'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入密码'},
                               )

    email = forms.EmailField(label="邮件",
                             required=True,
                             widget=widgets.TextInput(
                                 attrs={
                                     'id': 'email', 'class': 'form-control', 'placeholder': '邮件'}
                             ),
                             error_messages={'required': '请输入邮箱'},
                             )

    phone = forms.CharField(label="电话",
                            required=True,
                            error_messages={'required': '请输入电话'},
                            )

    # level = forms.ChoiceField(label="等级",
    #                         required=True,
    #                         error_messages={'required': '请输入等级'},
    #                         )
    #
    # state = forms.CharField(label="状态",
    #                         required=True,
    #                         error_messages={'required': '请输入状态'},
    #                         )

common/forms/orderInsertForm.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets


class OrderInsertForm(forms.Form):
    c_name = forms.CharField(label='客户姓名',
                             required=True,
                             strip=True,
                             min_length=2,
                             max_length=32,
                             widget=widgets.TextInput(
                                 attrs={'id': 'c_name', 'class': 'form-control', 'placeholder': '客户姓名'}),
                             validators=[
                                 RegexValidator(r'^[\u4E00-\u9FA5A-Za-z0-9_]+$', '不能输入特殊字符')
                             ],
                             error_messages={'required': '请输入姓名',
                                             'min_length': '格式不正确',
                                             'max_length': '格式不正确'
                                             },
                             )
    c_phone = forms.CharField(label='客户电话',
                              required=True,
                              strip=True,
                              min_length=11,
                              max_length=11,
                              widget=widgets.TextInput(
                                  attrs={'id': 'c_phone', 'class': 'form-control', 'placeholder': '客户电话'}),
                              validators=[RegexValidator(r'^1[3-9]\d{9}$', '手机号格式不正确')],
                              error_messages={'required': '请输入电话'},
                              )
    order = forms.CharField(label="订单",
                            required=False,
                            strip=True,
                            )
    remark = forms.CharField(label="备注",
                             required=False,
                             strip=True,
                             max_length=2048,
                             # validators=[RegexValidator(r'^[\u4E00-\u9FA5A-Za-z0-9_]+$', '不能输入特殊字符')],
                             )
    c_name = forms.CharField(label='客户姓名',
                             required=True, strip=True,
                             min_length=2, max_length=10,
                             widget=widgets.TextInput(
                                 attrs={'class': 'form-control', 'placeholder': '客户姓名'}),
                             validators=[RegexValidator(r'^[\u4E00-\u9FA5A-Za-z0-9_]+$', '不能输入特殊字符')],
                             error_messages={'required': '请输入姓名', 'min_length': '格式不正确',
                                             'max_length': '格式不正确'})
    c_phone = forms.CharField(label='客户电话',
                              required=True, strip=True,
                              min_length=11, max_length=11,
                              widget=widgets.TextInput(
                                  attrs={'class': 'form-control', 'placeholder': '客户电话'}),
                              validators=[RegexValidator(r'1[1-9][0-9]{9}', '手机号格式不正确')],
                              error_messages={'required': '请输入电话'})
    l_glasses = forms.CharField(label="L_产品",
                                required=False, strip=True,
                                max_length=20,
                                widget=widgets.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': '右眼镜片'}),
                                validators=[RegexValidator(r'^[\u4E00-\u9FA5A-Za-z0-9_]+$', '不能输入特殊字符')],
                                error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    l_sphere = forms.DecimalField(label="L_球镜",
                                  required=False,
                                  min_value=-24, max_value=16,
                                  max_digits=5, decimal_places=2,
                                  widget=widgets.TextInput(
                                      attrs={'class': 'form-control', 'placeholder': '右眼球镜'}),
                                  error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    l_astigmatic = forms.DecimalField(label="L_散光",
                                      required=False,
                                      min_value=0, max_value=8,
                                      max_digits=5, decimal_places=2,
                                      widget=widgets.TextInput(
                                          attrs={'class': 'form-control', 'placeholder': '右眼散光'}),
                                      error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    l_deviation = forms.IntegerField(label="L_偏位",
                                     required=False,
                                     min_value=0, max_value=180,
                                     widget=widgets.TextInput(
                                         attrs={'class': 'form-control', 'placeholder': '右眼偏位'}),
                                     error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    l_add = forms.IntegerField(label="L_渐进",
                               required=False,
                               min_value=50, max_value=400,
                               widget=widgets.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': '右眼渐进'}),
                               error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    l_pd = forms.IntegerField(label="瞳距",
                              required=False,
                              min_value=43, max_value=83,
                              widget=widgets.TextInput(
                                  attrs={'class': 'form-control', 'placeholder': '右眼瞳距'}),
                              error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    r_glasses = forms.CharField(label="R_产品",
                                required=False,
                                max_length=20,
                                widget=widgets.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': '左眼镜片'}),
                                validators=[RegexValidator(r'^[\u4E00-\u9FA5A-Za-z0-9_]+$', '不能输入特殊字符')],
                                error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    r_sphere = forms.DecimalField(label="R_球镜",
                                  required=False,
                                  min_value=-24, max_value=16,
                                  max_digits=5, decimal_places=2,
                                  widget=widgets.TextInput(
                                      attrs={'class': 'form-control', 'placeholder': '左眼球镜'}),
                                  error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    r_astigmatic = forms.DecimalField(label="R_散光",
                                      required=False,
                                      min_value=0, max_value=8,
                                      max_digits=5, decimal_places=2,
                                      widget=widgets.TextInput(
                                          attrs={'class': 'form-control', 'placeholder': '左眼散光'}),
                                      error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    r_deviation = forms.IntegerField(label="R_偏位",
                                     required=False,
                                     min_value=0, max_value=180,
                                     widget=widgets.TextInput(
                                         attrs={'class': 'form-control', 'placeholder': '左眼偏位'}),
                                     error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    r_add = forms.IntegerField(label="R_渐进",
                               required=False,
                               min_value=50, max_value=400,
                               widget=widgets.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': '左眼渐进'}),
                               error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    r_pd = forms.IntegerField(label="瞳距",
                              required=False,
                              min_value=43, max_value=83,
                              widget=widgets.TextInput(
                                  attrs={'class': 'form-control', 'placeholder': '左眼瞳距'}),
                              error_messages={'min_value': '超出范围', 'max_value': '超出范围'})
    frame = forms.CharField(label="镜框",
                            required=False,
                            max_length=256,
                            widget=widgets.TextInput(
                                attrs={'class': 'form-control', 'placeholder': '镜框'}),
                            validators=[RegexValidator(r'^[\u4E00-\u9FA5A-Za-z0-9_]+$', '不能输入特殊字符')],
                            error_messages={'max_value': '超出范围'})
    todo = forms.CharField(label="备注信息",
                           required=False, strip=True,
                           max_length=2048,
                           widget=widgets.Textarea(
                               attrs={'class': 'form-control', 'placeholder': '备注'}),
                           validators=[RegexValidator(r'^[\u4E00-\u9FA5A-Za-z0-9_]+$', '不能输入特殊字符')])

templates/maneu_order_v2/detail.html
{% extends 'maneu/base_admin.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/maneu_order_v2/order_detail.css' %}">
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 3%; margin-bottom: 5%">
        <div class="col-12 row">
            <div class="col-2">
                <form method="get" action="{% url 'maneu_order_v2:index' %}">
                    <div class="input-group input-group-sm">
                        <input type="submit" class="btn btn-primary" value="返回">
                    </div>
                </form>
            </div>
        </div>
        <br>
        <table class="table table-bordered table-sm text-left" id="textArea">
            <tr class="banner">
                <td colspan="9">
                    <b>客户信息（Guess information）</b>
                </td>
            </tr>
            <tr>
                <td>
                    <span>创建时间</span>
                </td>
                <td colspan="2">
                    <span>{{ order.time }}</span>
                </td>
                <td>
                    <span>姓名</span>
                </td>
                <td colspan="2">
                    <span>{{ order.name }}</span>
                </td>
                <td>
                    <span>电话</span>
                </td>
                <td colspan="2">
                    <span>{{ order.phone }}</span>
                </td>
            </tr>
            <tr class="banner">
                <td colspan="9">
                    <b>视力解决方案（Vision Solutions）</b>
                </td>
            </tr>
            <tr>
                <td>
                    <span>参数</span>
                </td>
                <td>
                    <span>裸眼视力 VA</span>
                </td>
                <td>
                    <span>球镜 Sph</span>
                </td>
                <td>
                    <span>柱镜 Cyl</span>
                </td>
                <td>
                    <span>轴位 Axial</span>
                </td>
                <td>
                    <span>棱镜 Pr</span>
                </td>
                <td>
                    <span>基底取向 FR</span>
                </td>
                <td>
                    <span>下加光 ADD</span>
                </td>
                <td>
                    <span>矫正视力 BSCVA</span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>右眼</span>
                </td>
                <td>
                    <span id="OD_VA"></span>
                </td>
                <td>
                    <span id="OD_SPH"></span>
                </td>
                <td>
                    <span id="OD_CYL"></span>
                </td>
                <td>
                    <span id="OD_AX"></span>
                </td>
                <td>
                    <span id="OD_PR"></span>
                </td>
                <td>
                    <span id="OD_FR"></span>
                </td>
                <td>
                    <span id="OD_ADD"></span>
                </td>
                <td>
                    <span id="OD_BCVA"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>左眼</span>
                </td>
                <td>
                    <span id="OS_VA"></span>
                </td>
                <td>
                    <span id="OS_SPH"></span>
                </td>
                <td>
                    <span id="OS_CYL"></span>
                </td>
                <td>
                    <span id="OS_AX"></span>
                </td>
                <td>
                    <span id="OS_PR"></span>
                </td>
                <td>
                    <span id="OS_FR"></span>
                </td>
                <td>
                    <span id="OS_ADD"></span>
                </td>
                <td>
                    <span id="OS_BCVA"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>使用需求</span>
                </td>
                <td colspan="8">
                    <span id="function"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>瞳距</span>
                </td>
                <td colspan="8">
                    <span id="PD"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>验光师建议</span>
                </td>
                <td colspan="8">
                    <span id="remark"></span>
                </td>
            </tr>
            <tr class="banner">
                <td colspan="9">
                    <b>产品订单信息（Product Orders）</b>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <span>类别</span>
                </td>
                <td colspan="2">
                    <span>品牌</span>
                </td>
                <td colspan="2">
                    <span>型号</span>
                </td>
                <td colspan="2">
                    <span>参数</span>
                </td>
                <td colspan="1">
                    <span>价格</span>
                </td>
            </tr>
            <tbody id="store_table"></tbody>
            <tr class="banner">
                <td colspan="9">
                    <b>注意事项（matters need attention）</b>
                </td>
            </tr>
            <tr>
                <td colspan="9">
                    <span>处方由眼科专家根据患者屈光不正性质、年龄、用眼需求等综合因素决定。</span>
                    <span>选择镜片、镜架及按眼科专家指导的配戴方法才能确保矫正效果和视觉健康。</span>
                    <span>数据为当时检查状态的结果，检查后如超过六个月配镜，建议复查。</span>
                </td>
            </tr>
        </table>
        <div class="col-12 row">
            <div class="col-2">
                <form method="post" action="{% url 'maneu_guest:detail' %}">
                    {% csrf_token %}
                    <input type="hidden" name="guess_id" value="{{ order.guess_id }}">
                    <div class="input-group input-group-sm">
                        <input type="submit" class="btn btn-primary" value="客户">
                    </div>
                </form>
            </div>
            <div class="col-2">
                <div class="input-group input-group-sm">
                    <button class="btn btn-primary" id="print_btn">打印</button>
                </div>
            </div>
            <div class="col-2">
                <form method="get" action="{% url 'maneu_order_v2:update' %}">
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <div class="input-group input-group-sm">
                        <input type="submit" class="btn btn-warning" value="修改">
                    </div>
                </form>
            </div>
            <div class="col-2">
                <form method="post" action="{% url 'maneu_order_v2:delete' %}">
                    {% csrf_token %}
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <div class="input-group input-group-sm">
                        <input type="submit" class="btn btn-danger" id="delete" value="删除">
                    </div>
                </form>
            </div>
        </div>
        <br>
        <table class="table">
            <tr>
                <td class="col-2">
                    <h5>售后记录</h5>
                </td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td class="col-2">
                    <span>时间</span>
                </td>
                <td class="col-9">
                    <span>内容</span>
                </td>
                <td class="col-1">
                    <div class="col-6 offset-6 input-group input-group-sm">
                        <input type="submit" class="btn btn-primary" value="添加">
                    </div>
                </td>
            </tr>
            <tr>
                <td class="col-11" colspan='3'>
                    <form id="serverInsert">
                        {% csrf_token %}
                        <div class="input-group input-group-sm">
                            <input type="text" name="content" class="form-control">
                            <input type="hidden" name="order_id" value="{{ order.id }}">
                            <input type="hidden" name="guess_id" value="{{ order.guess_id }}">
                            <input class="btn btn-primary" type="button" value="提交" id="serverInsertButton">
                        </div>
                    </form>
                </td>
            </tr>
            <tbody id="serverTable">
            {% if server %}
                {% for foo in server %}
                    <tr>
                        <td class="col-2">
                            <span>{{ foo.time }}</span>
                        </td>
                        <td class="col-9">
                            <span>{{ foo.content }}</span>
                        </td>
                        <td class="col-1">
                            <div class="col-6 offset-6 input-group input-group-sm">
                                <input type="button" class="btn btn-danger delete submit" value="删除" rel="{{ foo.id }}">
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td align="center" colspan="3">
                        <span>没有记录</span>
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block javascript %}
    <script type="application/javascript">
        maneu_store = {{ store|safe }};
        maneu_vision = {{ vision|safe }};
        service_delete = "{% url 'maneu_service:delete' %}"
        serverInsertUrl = "{% url 'maneu_service:testsInsert' %}"
    </script>
    <script type="application/javascript" src="https://cdn.bootcdn.net/ajax/libs/jQuery.print/1.6.2/jQuery.print.js"></script>
    <script type="application/javascript" src="{% static 'javascript/maneu/delete.js' %}"></script>
    <script type="application/javascript" src="{% static 'javascript/maneu/print.js' %}"></script>
    <script type="application/javascript" src="{% static 'javascript/maneu_order/order_detail.js' %}"></script>
    <script type="application/javascript" src="{% static 'javascript/maneu/serialize_moudels.js' %}"></script>
{% endblock %}

templates/maneu_order_v2/index.html
{% extends 'maneu/base_admin.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <!--内容栏-->
        <table class="table col-12">
            <tr>
                <td class="col-6" colspan="2">
                    <h5>零售订单管理系统</h5>
                </td>
                <td class="col-3">
                    <form method="get" action="{% url 'maneu_order_v2:search' %}">
                        <div class="input-group input-group-sm">
                            <input type="date" name="time" class="form-control" value="{{ time|safe }}">
                            <input type="submit" class="btn btn-primary" value="查询">
                        </div>
                    </form>
                </td>
                <td class="col-3">
                    <form method="get" action="{% url 'maneu_order_v2:search' %}">
                        <div class="input-group input-group-sm">
                            <input type="text" name="text" class="form-control" placeholder="使用手机或姓名查询">
                            <input type="submit" class="btn btn-primary" value="查询">
                        </div>
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                    <span>客户姓名</span>
                </td>
                <td>
                    <span>客户电话</span>
                </td>
                <td>
                    <span>录入时间</span>
                </td>
                <td align="right">
                    <form class="col-5" method="get" action="{% url 'maneu_order_v2:insert' %}">
                        <div class="input-group input-group-sm">
                            <input type="submit" class="btn btn-warning col-12" value='添加订单'>
                        </div>
                    </form>
                </td>
            </tr>
            {% if list %}
                {% for foo in list %}
                    <tr>
                        <td>
                            <span>{{ foo.name }}</span>
                        </td>
                        <td>
                            <span>{{ foo.phone }}</span>
                        </td>
                        <td>
                            <span>{{ foo.time }}</span>
                        </td>
                        <td align="right">
                            <div class="col-12 row">
                                <form class="col-3 offset-6" method="post" action="{% url 'maneu_order_v2:delete' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="order_id" value="{{ foo.id }}">
                                    <div class="input-group input-group-sm">
                                        <input type="submit" class="btn btn-danger col-12 delete" value="删除">
                                    </div>
                                </form>
                                <form class="col-3" method="post" action="{% url 'maneu_order_v2:detail' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="order_id" value="{{ foo.id }}">
                                    <div class="input-group input-group-sm">
                                        <input type="submit" class="btn btn-primary col-12" value="查看">
                                    </div>
                                </form>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4" align="center">
                        <span>没有订单</span>
                    </td>
                </tr>
            {% endif %}
        </table>
    </div>
{% endblock %}
{% block javascript %}
    <script type="application/javascript" src="{% static 'javascript/maneu/delete.js' %}"></script>
{% endblock %}