maneu/urls.py
from django.urls import include
from django.urls import path

from maneu.views import *

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('sendsms/', sendsms, name='sendsms'),
    path('login_api/', login_api, name='login_api'),
    path('maneu_admin/', include('maneu_admin.urls')),
    path('maneu_guest/', include('maneu_guest.urls')),
    path('maneu_index/', include('maneu_index.urls')),
    path('maneu_order/', include('maneu_order.urls')),
    path('maneu_report/', include('maneu_report.urls')),
]

maneu_guest/urls.py
from django.urls import path

from maneu_guest import views, api

app_name = 'maneu_guest'

urlpatterns = [
    path('', views.index, name='index'),
    path('insert/', views.insert, name='insert'),
    path('detail/', views.detail, name='detail'),
    path('api_search/', api.search, name='api_search'),
    path('api_insert/', api.insert, name='api_insert'),
    path('api_delete/', api.delete, name='api_delete'),
    path('api_detail/', api.detail, name='api_detail'),
    path('api_update/', api.update, name='api_update'),
]

user/urls.py
from django.urls import path

from user import api
from user import views

app_name = 'user'
urlpatterns = [
    # view
    path('list/', views.user_list, name='user_list'),
    path('logout/', views.user_logout, name='user_logout'),
    path('insert/', views.user_insert, name='user_insert'),
    path('update/', views.user_update, name='user_update'),
    path('detail/', views.user_detail, name='user_detail'),

    # api
    path('api_list/', api.user_list, name='api_user_list'),
    path('api_insert/', api.user_insert, name='api_user_insert'),
]

common/forms/InsertForm.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets


class UserInsertForm(forms.Form):
    username = forms.CharField(label="账号",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'username', 'class': 'form-control', 'placeholder': '账号'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入账号'},
                               )

    password = forms.CharField(label="密码",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'password', 'class': 'form-control', 'placeholder': '密码'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入密码'},
                               )

    email = forms.EmailField(label="邮件",
                             required=True,
                             widget=widgets.TextInput(
                                 attrs={
                                     'id': 'email', 'class': 'form-control', 'placeholder': '邮件'}
                             ),
                             error_messages={'required': '请输入邮箱'},
                             )

    phone = forms.CharField(label="电话",
                            required=True,
                            error_messages={'required': '请输入电话'},
                            )

    # level = forms.ChoiceField(label="等级",
    #                         required=True,
    #                         error_messages={'required': '请输入等级'},
    #                         )
    #
    # state = forms.CharField(label="状态",
    #                         required=True,
    #                         error_messages={'required': '请输入状态'},
    #                         )

maneu_guest/views.py
from django.shortcuts import render

from common.common import current_time, time_start, time_end


def index(request):
    return render(request, 'maneu_guest/index.html', {'timeS': time_start, 'timeE': time_end})


def insert(request):
    return render(request, 'maneu_guest/insert.html', {'time': current_time()})


def detail(request):
    return render(request, 'maneu_guest/detail.html', {'id': request.GET.get('id')})

templates/maneu_guest/index.html
{% extends 'maneu/base.html' %}
{% load static %}
{% block javascript %}
    <script type="application/javascript">
        web_detail = "{% url 'maneu_guest:detail' %}"
        api_search = "{% url 'maneu_guest:api_search' %}"
        api_delete = "{% url 'maneu_guest:api_delete' %}"
    </script>
    <script type="application/javascript" src='{% static "javascript/maneu_order/index.js" %}'></script>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-12 row">
            <div class="col-4">
                <h5>用户管理</h5>
            </div>
            <div class="col-8">
                <div class="vertical1 input-group">
                    <span class="input-group-text">开始时间</span>
                    <input autocomplete="off" class="form-control" id="timeS" min="2020-01-01 00:00" max="{{ timeE }}" type="datetime-local" value="{{ timeS }}">
                    <span class="input-group-text">结束时间</span>
                    <input autocomplete="off" class="form-control" id="timeE" min="2020-01-01 00:00" max="{{ timeE }}" type="datetime-local" value="{{ timeE }}">
                    <input type="text" class="col-12 form-control" id="value" placeholder="使用手机或姓名查询">
                    <input type="button" class="btn btn-primary" id="search_button" value="搜索">
                </div>
            </div>
        </div>
        <hr style="color:white;">
        <div class="col-12 row">
            <div class="col-2">
                <p>录入时间</p>
            </div>
            <div class="col-1">
                <p>客户姓名</p>
            </div>
            <div class="col-1">
                <p>客户电话</p>
            </div>
            <div class="col-7">
                <p>订单备注</p>
            </div>
            <div class="col-1">
                <form method="get" action="{% url 'maneu_guest:insert' %}">
                    <div class='input-group input-group-sm'>
                        <input type="submit" class="col-12 btn btn-warning" value='添加订单'>
                    </div>
                </form>
            </div>
        </div>
        <hr style="color:white;">
        <div id="body"></div>
    </div>
{% endblock %}

templates/maneu_guest/insert.html
{% extends 'maneu/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form class="vertical2" method="get" action="{% url 'maneu_guest:index' %}">
            <div class="vertical1 col-1">
                <div class="input-group input-group-sm">
                    <input type="submit" class="btn btn-primary" value="返回列表">
                </div>
            </div>
        </form>
        <hr>

        {# 基础数据 #}
        <form class="vertical2">
            {# 客户数据 #}
            <h5>客户数据</h5>
            <div class="vertical1 col-3">
                <div class="input-group input-group-sm">
                    <span class="input-group-text col-3">时间</span>
                    <input autocomplete="off" class="form-control" name="time" type="datetime-local" value="{{ time }}">
                </div>
            </div>
            <div class="vertical1 col-3">
                <div class="input-group input-group-sm">
                    <span class="input-group-text col-3">电话</span>
                    <input autocomplete="off" class="form-control" type="text" name="call">
                </div>
            </div>
            <div class="vertical1 col-3">
                <div class="input-group input-group-sm">
                    <span class="input-group-text col-3">姓名</span>
                    <input autocomplete="off" class="form-control" type="text" name="name">
                </div>
            </div>
            <div class="vertical1 col-9">
                <div class="input-group input-group-sm">
                    <span class="input-group-text col-1">性别</span>
                    <input autocomplete="off" class="form-control" type="text" name="sex" list="sex">
                    <span class="input-group-text col-1">年龄</span>
                    <input autocomplete="off" class="form-control" type="text" name="age" list="age">
                    <span class="input-group-text col-1">眼位</span>
                    <input autocomplete="off" class="form-control" type="text" name="OT" list="OT">
                    <span class="input-group-text col-1">主视眼</span>
                    <input autocomplete="off" class="form-control" type="text" name="EM" list="EM">
                    <span class="input-group-text col-1">病族史</span>
                    <input autocomplete="off" class="form-control" type="text" name="DFH" list="DFH">
                </div>
            </div>
            <div class="vertical1 col-9">
                <div class="input-group input-group-sm">
                    <span class="input-group-text col-1">备注</span>
                    <input autocomplete="off" class="form-control" type="text" name="remark">
                </div>
            </div>
        </form>
        <hr>

        {# 提交或返回按钮 #}
        <form class="vertical2">
            <div class="vertical1 col-1">
                <div class="input-group input-group-sm">
                    <input type="button" class="btn btn-danger" id="insert" value="提交数据">
                </div>
            </div>
        </form>
    </div>


    <div>
        <datalist id="DFH">
            <option>有</option>
            <option>无</option>
        </datalist>
        <datalist id="EM">
            <option>右</option>
            <option>左</option>
        </datalist>
        <datalist id="OT">
            <option>正位眼</option>
            <option>斜视</option>
        </datalist>
        <datalist id="sex">
            <option>男</option>
            <option>女</option>
        </datalist>
    </div>

{% endblock %}
{% block javascript %}
    <script>
        guest_index = "{% url 'maneu_guest:index' %}"
        guest_api = "{% url 'maneu_guest:api_insert' %}"
    </script>
    <script type="application/javascript" src="{% static 'javascript/maneu_guest/insert.js' %}"></script>
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/maneu_guest/insert.css' %}">
{% endblock %}