maneu/urls.py
from django.urls import include
from django.urls import path

from maneu.views import *

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('sendsms/', sendsms, name='sendsms'),
    path('login_api/', login_api, name='login_api'),
    path('maneu_admin/', include('maneu_admin.urls')),
    path('maneu_guest/', include('maneu_guest.urls')),
    path('maneu_index/', include('maneu_index.urls')),
    path('maneu_order/', include('maneu_order.urls')),
    path('maneu_report/', include('maneu_report.urls')),
]

maneu_admin/urls.py
from django.urls import path

from maneu_admin import views, api

app_name = 'maneu_admin'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert/', views.user_insert, name='insert'),
    path('api_detail/', api.detail, name='api_detail'),
    path('api_update/', api.update, name='api_update'),
]

maneu_guest/urls.py
from django.urls import path

from maneu_guest import views, api

app_name = 'maneu_guest'

urlpatterns = [
    path('', views.index, name='index'),
    path('insert/', views.insert, name='insert'),
    path('detail/', views.detail, name='detail'),
    path('api_search/', api.search, name='api_search'),
    path('api_insert/', api.insert, name='api_insert'),
    path('api_delete/', api.delete, name='api_delete'),
    path('api_detail/', api.detail, name='api_detail'),
    path('api_update/', api.update, name='api_update'),
]

user/urls.py
from django.urls import path

from user import api
from user import views

app_name = 'user'
urlpatterns = [
    # view
    path('list/', views.user_list, name='user_list'),
    path('logout/', views.user_logout, name='user_logout'),
    path('insert/', views.user_insert, name='user_insert'),
    path('update/', views.user_update, name='user_update'),
    path('detail/', views.user_detail, name='user_detail'),

    # api
    path('api_list/', api.user_list, name='api_user_list'),
    path('api_insert/', api.user_insert, name='api_user_insert'),
]

common/forms/InsertForm.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets


class UserInsertForm(forms.Form):
    username = forms.CharField(label="账号",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'username', 'class': 'form-control', 'placeholder': '账号'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入账号'},
                               )

    password = forms.CharField(label="密码",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'password', 'class': 'form-control', 'placeholder': '密码'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入密码'},
                               )

    email = forms.EmailField(label="邮件",
                             required=True,
                             widget=widgets.TextInput(
                                 attrs={
                                     'id': 'email', 'class': 'form-control', 'placeholder': '邮件'}
                             ),
                             error_messages={'required': '请输入邮箱'},
                             )

    phone = forms.CharField(label="电话",
                            required=True,
                            error_messages={'required': '请输入电话'},
                            )

    # level = forms.ChoiceField(label="等级",
    #                         required=True,
    #                         error_messages={'required': '请输入等级'},
    #                         )
    #
    # state = forms.CharField(label="状态",
    #                         required=True,
    #                         error_messages={'required': '请输入状态'},
    #                         )

maneu_admin/views.py
from django.shortcuts import render

from maneu_admin import service


def index(request):
    return render(request, 'maneu_admin/index.html', {'id': request.session.get('id')})


def user_insert(request):
    if request.method == 'POST':
        if request.POST['gift_password'] == '214772680':
            updata = service.user_insert(username=request.POST['username'],
                                         nickname=request.POST['nickname'],
                                         password=request.POST['password'],
                                         phone=request.POST['phone'],
                                         email=request.POST['email'])
    return render(request, 'maneu_admin/insert.html')

templates/maneu_admin/detail.html
{% extends 'maneu/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <table class="table" style="margin-top: 3%; margin-bottom: 5%">
            <tr class="blue">
                <td colspan="3">
                    <h5>商家资料</h5>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>名称</span>
                </td>
                <td style="width: 90%" colspan='2'>
                    <span>{{ maneu_admin.nickname }}</span>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>账号</span>
                </td>
                <td style="width: 90%" colspan='2'>
                    <span>{{ maneu_admin.username }}</span>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>地址</span>
                </td>
                <td style="width: 90%" colspan='2'>
                    <span>{{ maneu_admin.localtion }}</span>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>电话</span>
                </td>
                <td style="width: 90%" colspan='2'>
                    <span>{{ maneu_admin.phone }}</span>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>邮件</span>
                </td>
                <td style="width: 90%" colspan='2'>
                    <span>{{ maneu_admin.email }}</span>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>创建时间</span>
                </td>
                <td style="width: 90%" colspan='2'>
                    <span>{{ maneu_admin.create_time }}</span>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>商家特色</span>
                </td>
                <td style="width: 90%" colspan='2'>
                    <span>{{ maneu_admin.remark }}</span>
                </td>
            </tr>
            <tr class="blue">
                <td style="width: 10%">
                    <span>账户操作</span>
                </td>
                <td style="width: 10%">
                    <div class="input-group input-group-sm">
                        <a class="btn btn-warning" style="color: black"
                           href="{% url 'maneu_admin:updata' %}">修改资料</a>
                    </div>
                </td>
                <td style="width: 80%">
                    <div class="input-group input-group-sm">
                        <a class="btn btn-warning" style="color: black" href="{% url 'login' %}">退出登录</a>
                    </div>
                </td>
            </tr>
        </table>
    </div>
{% endblock %}
{% block javascript %}
    <script src="{% static 'javascript/maneu/windos_back.js' %}"></script>
{% endblock %}

templates/maneu_admin/index.html
{% extends 'maneu/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form class="vertical2" method="get" action="{% url 'maneu_guest:index' %}">
            <div class="vertical1 col-1">
                <div class="input-group input-group-sm">
                    <input type="submit" class="btn btn-primary" value="返回列表">
                </div>
            </div>
        </form>
        <hr>

        {# 基础数据 #}
        <form class="vertical2">
            {# 客户数据 #}
            <h5>基础数据</h5>
            <div class="vertical1 col-9">
                <div class="input-group input-group-sm">
                    <span class="input-group-text">时间</span>
                    <input autocomplete="off" class="form-control" id="time" type="datetime-local" value="{{ time }}">
                </div>
            </div>
            <div class="vertical1 col-9">
                <div class="input-group input-group-sm">
                    <span class="input-group-text">电话</span>
                    <input autocomplete="off" class="form-control" type="text" id="phone">
                </div>
            </div>
            <div class="vertical1 col-9">
                <div class="input-group input-group-sm">
                    <span class="input-group-text">店名</span>
                    <input autocomplete="off" class="form-control" type="text" id="nickname">
                </div>
            </div>
            <div class="vertical1 col-9">
                <div class="input-group input-group-sm">
                    <span class="input-group-text">地址</span>
                    <input autocomplete="off" class="form-control" type="text" id="location">
                </div>
            </div>
            <div class="vertical1 col-9">
                <div class="input-group input-group-sm">
                    <span class="input-group-text">简介</span>
                    <input autocomplete="off" class="form-control" type="text" id="content">
                </div>
            </div>
        </form>
        <hr>

        {# 提交或返回按钮 #}
        <form class="vertical2">
            <div class="vertical1 col-1">
                <div class="input-group input-group-sm">
                    <input type="button" class="btn btn-danger" id="update" value="提交数据">
                </div>
            </div>
        </form>
    </div>

{% endblock %}
{% block javascript %}
    <script>
        admin_id = "{{ id }}"
        admin_index = "{% url 'maneu_admin:index' %}"
        admin_detail = "{% url 'maneu_admin:api_detail' %}"
        admin_update = "{% url 'maneu_admin:api_update' %}"
    </script>
    <script type="application/javascript" src="{% static 'javascript/maneu_admin/index.js' %}"></script>
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/maneu_guest/insert.css' %}">
{% endblock %}

templates/maneu_admin/insert.html
{% extends 'maneu/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="col-md-6 offset-md-3" style="margin-top: 20%; margin-bottom: 20%">
            <form method="post" action="{% url 'maneu_admin:insert' %}">
                {% csrf_token %}
                <div class="input-group input-group-sm mb-2">
                    <span class="input-group-text">邀请密码</span>
                    <input type="text" name="gift_password" id="gift_password" class="form-control">

                </div>
                <div class="input-group input-group-sm mb-2">
                    <span class="input-group-text">登录账户</span>
                    <input type="text" name="username" id="username" class="form-control">

                </div>
                <div class="input-group input-group-sm mb-2">
                    <span class="input-group-text">登录密码</span>
                    <input type="text" name="password" id="password" class="form-control">

                </div>

                <div class="input-group input-group-sm mb-2">
                    <span class="input-group-text">商家名称</span>
                    <input type="text" name="nickname" id="nickname" class="form-control" value="{{ user.nickname }}">

                </div>
                <div class="input-group input-group-sm mb-2">
                    <span class="input-group-text">手机号码</span>
                    <input type="text" name="phone" id="phone" value="{{ user.phone }}" class="form-control">

                </div>
                <div class="input-group input-group-sm mb-2">
                    <span class="input-group-text">电子邮箱</span>
                    <input type="text" name="email" id="email" value="{{ user.email }}" class="form-control">

                </div>
                <div class="input-group input-group-sm mb-2">
                    <span class="input-group-text">特色服务</span>
                    <input type="text" name="remark" id="remark" value="{{ user.remark }}" class="form-control">

                </div>
                <br>
                <p>{{ msg }}</p>
                <input type="submit" class="col-md-12 btn btn-primary">
            </form>
            <a href="{% url 'maneu_admin:index' %}" type="button" class="col-md-12 btn btn-warning">返回</a>
        </div>
    </div>
{% endblock %}