maneu/urls.py
from django.urls import include
from django.urls import path

from maneu.views import *

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('sendsms/', sendsms, name='sendsms'),
    path('login_api/', login_api, name='login_api'),
    path('maneu_admin/', include('maneu_admin.urls')),
    path('maneu_guest/', include('maneu_guest.urls')),
    path('maneu_index/', include('maneu_index.urls')),
    path('maneu_order/', include('maneu_order.urls')),
    path('maneu_report/', include('maneu_report.urls')),
]

maneu_admin/urls.py
from django.urls import path

from maneu_admin import views, api

app_name = 'maneu_admin'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert/', views.user_insert, name='insert'),
    path('api_detail/', api.detail, name='api_detail'),
    path('api_update/', api.update, name='api_update'),
]

maneu_batch/urls.py
from django.urls import path

from maneu_batch import views

app_name = 'maneu_batch'
urlpatterns = [
    # views
    path('index/', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('insert/', views.insert, name='insert'),
    path('delete/', views.delete, name='delete'),
    path('detail/', views.detail, name='detail'),
]

maneu_class/urls.py
from django.urls import path

from maneu_class import views

app_name = 'maneu_class'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('class_insert/', views.class_insert, name='class_insert'),
]

maneu_guest/urls.py
from django.urls import path

from maneu_guest import views, api

app_name = 'maneu_guest'

urlpatterns = [
    path('', views.index, name='index'),
    path('insert/', views.insert, name='insert'),
    path('detail/', views.detail, name='detail'),
    path('api_search/', api.search, name='api_search'),
    path('api_insert/', api.insert, name='api_insert'),
    path('api_delete/', api.delete, name='api_delete'),
    path('api_detail/', api.detail, name='api_detail'),
    path('api_update/', api.update, name='api_update'),
]

user/urls.py
from django.urls import path

from user import api
from user import views

app_name = 'user'
urlpatterns = [
    # view
    path('list/', views.user_list, name='user_list'),
    path('logout/', views.user_logout, name='user_logout'),
    path('insert/', views.user_insert, name='user_insert'),
    path('update/', views.user_update, name='user_update'),
    path('detail/', views.user_detail, name='user_detail'),

    # api
    path('api_list/', api.user_list, name='api_user_list'),
    path('api_insert/', api.user_insert, name='api_user_insert'),
]

maneu/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
import uuid

from django.db import models


class ManeuAdmin(models.Model):
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid1, editable=False)
    username = models.CharField(max_length=36)
    password = models.CharField(max_length=36)
    nickname = models.CharField(max_length=36)
    email = models.CharField(max_length=36)
    phone = models.CharField(max_length=36)
    level = models.CharField(max_length=36)
    state = models.CharField(max_length=36)
    time = models.DateTimeField(blank=True, null=True)
    content = models.CharField(max_length=512, blank=True, null=True)
    location = models.CharField(max_length=512, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'maneu_admin'
        unique_together = (('id', 'username'),)


class ManeuGuest(models.Model):
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid1, editable=False)
    admin_id = models.CharField(max_length=36, blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    remark = models.TextField(blank=True, null=True)
    sex = models.CharField(max_length=36, blank=True, null=True)
    age = models.CharField(max_length=36, blank=True, null=True)
    dfh = models.CharField(max_length=36, blank=True, null=True)
    ot = models.CharField(max_length=36, blank=True, null=True)
    em = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'maneu_guest'


class ManeuOrder(models.Model):
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid1, editable=False)
    admin_id = models.CharField(max_length=36)
    guest_id = models.CharField(max_length=36)
    store_id = models.CharField(max_length=36)
    report_id = models.CharField(max_length=36)
    time = models.DateTimeField()
    name = models.CharField(max_length=36)
    phone = models.CharField(max_length=36)
    remark = models.CharField(max_length=512)
    content = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'maneu_order'


class ManeuReport(models.Model):
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid1, editable=False)
    admin_id = models.CharField(max_length=36, blank=True, null=True)
    guest_id = models.CharField(max_length=36, blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    remark = models.TextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'maneu_report'


class ManeuService(models.Model):
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid1, editable=False)
    time = models.DateTimeField()
    order_id = models.CharField(max_length=36, blank=True, null=True)
    admin_id = models.CharField(max_length=36)
    guess_id = models.CharField(max_length=36)
    content = models.CharField(max_length=300, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'maneu_service'


class ManeuStore(models.Model):
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid1, editable=False)
    time = models.DateTimeField()
    order_id = models.CharField(max_length=36)
    admin_id = models.CharField(max_length=36)
    guess_id = models.CharField(max_length=36)
    content = models.TextField()

    class Meta:
        managed = False
        db_table = 'maneu_store'


class ManeuUsers(models.Model):
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid1, editable=False)
    nickname = models.CharField(max_length=36)
    username = models.CharField(unique=True, max_length=36)
    password = models.CharField(max_length=36)
    email = models.CharField(max_length=36)
    phone = models.CharField(max_length=36)
    level = models.IntegerField()
    state = models.IntegerField()
    create_time = models.DateTimeField()
    remark = models.CharField(max_length=255, blank=True, null=True)
    localtion = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'maneu_users'

common/forms/loginForm.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets

from maneu_admin.serivce import find_username_password


class LoginForm(forms.Form):
    username = forms.CharField(label="账号",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={
                                       'id': 'username', 'class': 'form-control', 'placeholder': '账号'}
                               ),
                               validators=[RegexValidator(
                                   r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入账号'},
                               )
    password = forms.CharField(label="密码",
                               required=True,
                               strip=True,
                               widget=widgets.PasswordInput(
                                   attrs={
                                       'id': 'password', 'class': 'form-control', 'placeholder': '密码'}
                               ),
                               validators=[RegexValidator(
                                   r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入密码'},
                               )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        verify = find_username_password(username, password)
        if verify == None:
            raise forms.ValidationError('登录失败')

maneu/forms/loginForm.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets

from maneu_users.serivce import find_username_password


class LoginForm(forms.Form):
    username = forms.CharField(label="账号",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={
                                       'id': 'username', 'class': 'form-control', 'placeholder': '账号'}
                               ),
                               validators=[RegexValidator(
                                   r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入账号'},
                               )
    password = forms.CharField(label="密码",
                               required=True,
                               strip=True,
                               widget=widgets.PasswordInput(
                                   attrs={
                                       'id': 'password', 'class': 'form-control', 'placeholder': '密码'}
                               ),
                               validators=[RegexValidator(
                                   r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入密码'},
                               )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        verify = find_username_password(username, password)
        if verify == None:
            raise forms.ValidationError('登录失败')

maneu_users/forms/loginForm.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets

from maneu_users.serivce import find_username_password


class LoginForm(forms.Form):
    username = forms.CharField(label="账号",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={
                                       'id': 'username', 'class': 'form-control', 'placeholder': '账号'}
                               ),
                               validators=[RegexValidator(
                                   r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入账号'},
                               )
    password = forms.CharField(label="密码",
                               required=True,
                               strip=True,
                               widget=widgets.PasswordInput(
                                   attrs={
                                       'id': 'password', 'class': 'form-control', 'placeholder': '密码'}
                               ),
                               validators=[RegexValidator(
                                   r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入密码'},
                               )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        verify = find_username_password(username, password)
        if verify == None:
            raise forms.ValidationError('登录失败')

users/forms/loginForm.py
from captcha.fields import CaptchaField
from django import forms
from django.core.validators import RegexValidator
from django.forms import widgets


class LoginForm(forms.Form):

    username = forms.CharField(label="账号",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'username', 'class': 'form-control', 'placeholder': '账号'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入账号'},
                               )

    password = forms.CharField(label="密码",
                               required=True,
                               strip=True,
                               widget=widgets.TextInput(
                                   attrs={'id': 'password', 'class': 'form-control', 'placeholder': '密码'}
                               ),
                               validators=[RegexValidator(r'^[A-Za-z0-9_]+$', '只支持数字和字母')],
                               error_messages={'required': '请输入密码'},
                               )

    captcha = CaptchaField(label="验证码",
                           required=True,
                           error_messages={"required": "验证码不能为空",
                                           "invalid": "验证码错误"}
                           )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username != 'unlock' and password != 'XMacheNike':
            raise forms.ValidationError('登录失败')

maneu/views.py
from django.http import JsonResponse
from django.shortcuts import render

from common import common
from common.verify import *
from maneu import service
from maneu.models import *


def index(request):
    """
    首页
    """
    return render(request, 'maneu/index.html')


def login(request):
    """
    登录模块
    获取session key并根据sessionkey 判断用户是否已经登录
    """
    return render(request, 'maneu/login.html')


def login_api(request):
    call = is_call(request.GET.get('call'))
    code = is_code(request.GET.get('code'))
    if code and call:
        try:
            content=service.admin_login(call,code)
            request.session['ip'] = common.getip(request)
            request.session['id'] = content.id
            request.session['nickname'] = content.nickname
            content = {'status': True, 'message': '', 'data': {}}
        except Exception as e:
            content = {'status': False, 'message': str(e), 'data': {}}
    else:
        content = {'status': False, 'message': '', 'data': {}}
    return JsonResponse(content)


def logout(request):
    code = is_code(request.session.get('id'))

    if code:
        request.session['ip'] = None
        request.session['id'] = None
        request.session['nickname'] = None
        data = service.admin_logout(code)
        if data:
            content = {'status': True, 'message': '', 'data': {}}
        else:
            content = {'status': False, 'message': '123', 'data': {}}
    else:
        content = {'status': False, 'message': '456', 'data': {}}

    return render(request, 'maneu/login.html')


def sendsms(request):
    phone_number = is_call(request.GET.get('call'))

    if phone_number:
        random_num = common.get_random_code()
        data = service.sendsms(call=phone_number, code=random_num)
        if data:
            response = common.sendsms(call=phone_number, code=random_num)
            if response['Code'] == 'OK':
                content = {'status': True, 'message': 'OK', 'data': {}}
            else:
                content = {'status': False, 'message': response["Message"], 'data': {}}
        else:
            content = {'status': False, 'message': '请输入正确的手机号', 'data': {}}
    else:
        content = {'status': False, 'message': '请输入正确的手机号', 'data': {}}

    return JsonResponse(content)

def test(request):
    adminList=['36483774080401481140071775853431',
               '23208668181988748078136965958996']

    for i in adminList:
        ManeuAdmin.objects.filter(id=i).update(id='794ecfda-44d2-11ed-818f-00163e02ac92')
        ManeuOrder.objects.filter(admin_id=i).update(id='794ecfda-44d2-11ed-818f-00163e02ac92')
        ManeuGuest.objects.filter(admin_id=i).update(id='794ecfda-44d2-11ed-818f-00163e02ac92')
        ManeuReport.objects.filter(admin_id=i).update(id='794ecfda-44d2-11ed-818f-00163e02ac92')
        ManeuStore.objects.filter(admin_id=i).update(id='794ecfda-44d2-11ed-818f-00163e02ac92')
        ManeuService.objects.filter(admin_id=i).update(id='794ecfda-44d2-11ed-818f-00163e02ac92')

    return JsonResponse({'id':'794ecfda-44d2-11ed-818f-00163e02ac92'})

templates/maneu/admin.html
{% extends 'maneu/base_all.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/maneu/login.css' %}">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="login-wrapper">
            <div class="header">徕可管理系统</div>
            <div class="form-wrapper">
                <form method="post" action="{% url 'login' %}" class="test1">
                    {% csrf_token %}
                    <label for="username">账号:</label>
                    <input type="text" name="username" class="input-item" placeholder="username" autocomplete="off">
                    <label for="password">密码:</label>
                    <input type="password" name="password" class="input-item" placeholder="password" autocomplete="off"><br>
                    {% if msg %}<span class="msg">{{msg}}</span>{% endif %}
                    <input type="submit" class="btn" value="登录">
                </form>
                <a style="color: white" href="{% url 'index' %}">
                    <button class="btn">返回</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/maneu/back.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>徕可</title>
    <link rel="icon" href="{% static 'images/maneu/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'css/maneu/login.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <!--  popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
</head>

<body>
<div class="container-fluid">
    <div class="login-wrapper">
        <div class="header">徕可管理系统</div>
        <div class="form-wrapper">
            <form method="post" action="{% url 'login' %}" class="test1">
                {% csrf_token %}
                <label for="username">账号:</label>
                <input type="text" name="username" class="input-item" placeholder="username" autocomplete="off">
                <label for="password">密码:</label>
                <input type="password" name="password" class="input-item" placeholder="password" autocomplete="off"><br>
                {% if msg %}<span class="msg">{{ msg }}</span>{% endif %}
                <input type="submit" class="btn" value="登录">
            </form>
            <a class="button" href="{% url 'index' %}">
                <button class="btn">返回</button>
            </a>
        </div>
    </div>
</div>
</body>

<footer class="fixed-bottom text-center">
    <a href="https://beian.miit.gov.cn">粤ICP备2023070483号</a>
</footer>
</html>

templates/maneu/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>徕可</title>
    <link rel="icon" href="{% static 'images/maneu/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'css/maneu/base.css' %}">
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link rel="stylesheet"
          href="https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/twitter-bootstrap/5.1.3/css/bootstrap.min.css">
    <!--  popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/popper.js/2.11.2/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/twitter-bootstrap/5.1.3/js/bootstrap.min.js"></script>
    <script src="https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/jquery/2.1.3/jquery.min.js"></script>
</head>


<body class="blue">
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <img style="height: 30px" src="{% static 'images/maneu/logo.svg' %}">
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link">数据可视化</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_order:index' %}">订单管理</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_report:index' %}">报告管理</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_guest:index' %}">客户管理</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'maneu_admin:index' %}" id="navbardrop"
                   data-bs-toggle="dropdown">个人中心</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'maneu_admin:index' %}">修改资料</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">退出登录</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
{% block content %} {% endblock %}
{% block css %}{% endblock %}
{% block javascript %}{% endblock %}
</body>


<footer class="text-center">
    <a href="https://beian.miit.gov.cn">粤ICP备2023070483号</a>
</footer>
</html>

templates/maneu/base0.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>徕可</title>
    <link rel="icon" href="{% static 'img/logo16x9.svg' %}">
    <link rel="stylesheet" href="{% static 'css/maneu/base.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <!--  popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
</head>
<body class="blue">
{% block content %}{% endblock %}
{% block css %}{% endblock %}
{% block js %}{% endblock %}
</body>
<footer class="fixed-bottom text-center">
    <a style="color: #FCDA5E" href="https://beian.miit.gov.cn">粤ICP备2020134991号</a>
</footer>
</html>

templates/maneu/base_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>徕可</title>
    <link rel="icon" href="{% static 'images/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'css/maneu/base.css' %}">
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <!--  popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
</head>

<body class="blue">
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <img style="height: 30px" src="{% static 'images/logo.svg' %}">
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_index:index' %}">数据可视化</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_order:index' %}">零售管理</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_guest:index' %}">客户管理</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-bs-toggle="dropdown">个人中心</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'maneu_admin:user_detail' %}">查看资料</a>
                    <a class="dropdown-item" href="{% url 'maneu_admin:user_updata' %}">修改资料</a>
                    <a class="dropdown-item" href="{% url 'login' %}">退出登录</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
{% block css %}{% endblock %}
{% block javascript %}{% endblock %}
{% block content %} {% endblock %}
</body>
<footer class="text-center" style="margin: 2%">
    <a style="color: #FFC048;" href="https://beian.miit.gov.cn">粤ICP备2023070483号</a>
</footer>
</html>

templates/maneu/base_uesrs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>徕可</title>
    <link rel="icon" href="{% static 'img/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'css/maneu/base.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <!--  popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
</head>

<body class="blue">
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="{% url 'index' %}">
        <img style="height: 30px" src="{% static 'img/logo.svg' %}">
    </a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_datalogs:index' %}">数据可视化(开发中)</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_order:index' %}">零售管理</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_batch:index' %}">批发管理</a>
            </li>
            {#            <li class="nav-item">#}
            {#                <a class="nav-link" href="{% url 'maneu_class:index' %}">商品管理</a>#}
            {#            </li>#}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_alterSales:index' %}">售后管理</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'maneu_client:index' %}">客户管理</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-bs-toggle="dropdown">个人中心</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'maneu_users:user_detail' %}">查看资料</a>
                    <a class="dropdown-item" href="{% url 'maneu_users:user_updata' %}">修改资料</a>
                    <a class="dropdown-item" href="{% url 'login' %}">退出登录</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
{% block css %}{% endblock %}
{% block content %} {% endblock %}
{% block javascript %}{% endblock %}
<div class="fixed-bottom text-center">
    <a style="color: #FCDA5E" href="https://beian.miit.gov.cn">粤ICP备2020134991号</a>
</div>
</body>
</html>